# 安装
alias aptin='sudo apt-get install'

# 卸载
alias aptre='sudo apt-get autoremove'

# 更新
alias ud='sudo apt-get update'

# 蝴蝶
alias eth0='/home/alic/Shell/Extra/butterfly/eth0.sh'
alias wlan0='/home/alic/Shell/Extra/butterfly/wlan0.sh'

# 更新host
alias uphost='sudo /home/alic/Shell/Extra/hosts/hosts.sh'

# apache2操作
alias staa='sudo service apache2 start'
alias stoa='sudo service apache2 stop'
alias resa='sudo service apache2 restart'

# ssh
alias sshserver='ssh -i /home/alic/Shell/Extra/server/.119.29.88.222 ubuntu@samego.com'
alias sshpi='ssh pi@172.16.168.115'
